name: deploy blog

on:
  # 手动
  workflow_dispatch:
  # 自动
  push:
    branches:
      - master
  # 远程
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 签出
      - name: checkout
        uses: actions/checkout@v3
      # 拉取子模块
      - name: pull submodule
        run: git submodule update --init --recursive
      # 设置访问权限
      - name: set deploy keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key:  |
                        ${{ secrets.PRIVATE_SSH_KEY }}
                        ${{ secrets.PRIVATE_SSH_KEY_POSTS }}
      # 拉取翻译文章
      - name: clone Paper_translation
        run: git clone git@github.com:qiuqingyun/Paper_translation.git
      # 拉取其他文章
      - name: clone posts
        run: git clone git@github.com:qiuqingyun/posts.git source/_posts/posts
      # 转换markdown文件
      - name: convert markdowns
        run: python .github/scripts/convert.py
      - name: ls
        run: ls -lhR
      # 使用 node:14
      - name: setup Node.js 14
        uses: actions/setup-node@main
        with:
          node-version: 14
      # npm install
      - name: npm install
        run: |
          npm install -g hexo-cli
          npm install
        env:
          CI: true
      # build
      - name: hexo build
        run: |
          hexo clean
          hexo generate
        env:
          CI: true
      # 部署到云端
      - name: deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}