name: deploy blog

on:
  # 手动
  workflow_dispatch:
  # 自动
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 签出
      - name: checkout
        uses: actions/checkout@v3
      # 拉取子模块
      - name: pull submodule
        run: git submodule update --init --recursive
      # 设置访问权限
      - name: set deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # 拉取文章
      - name: clone Paper_translation
        run: git clone https://github.com/qiuqingyun/Paper_translation.git
      # 转换markdown文件
      - name: convert markdowns
        run: python .github/scripts/convert.py
      # 使用 node:14
      - name: setup Node.js 14
        uses: actions/setup-node@main
        with:
          node-version: 14
      # npm install
      - name: npm install
        run: |
          cd blog
          npm install -g hexo-cli
          npm install
        env:
          CI: true
      # build
      - name: hexo build
        run: |
          cd blog
          hexo clean
          hexo generate
        env:
          CI: true
      # 部署到云端
      - name: deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "blog/public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}